apiVersion: apps/v1
kind: Deployment
metadata:
  name: savannah-ecommerce
  labels:
    app: savannah-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: savannah-ecommerce
  template:
    metadata:
      labels:
        app: savannah-ecommerce
    spec:
      containers:
      - name: savannah-ecommerce
        image: ${DOCKER_REGISTRY}/savannah-ecommerce:${IMAGE_TAG}
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: savannah_ecommerce.settings
        - name: DB_NAME
          value: savannah_db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: REDIS_URL
          value: redis://redis:6379/0
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15 