apiVersion: v1
kind: Service
metadata:
  name: savannah-ecommerce
  labels:
    app: savannah-ecommerce
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: savannah-ecommerce 