# Generated by Django 4.2.7 on 2025-06-01 09:50

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_options_product_image_product_views_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
