version: '3.8'

services:
  db:
    image: postgres:15
    container_name: savannah_postgres
    environment:
      POSTGRES_DB: savannah_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: savannah_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local