# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: savannah_db
        ports:
          - 5432:5432
        # Add these settings to ensure PostgreSQL is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PYTHONPATH: ${{ github.workspace }}
      DJANGO_SETTINGS_MODULE: savannah_ecommerce.ci_settings
      DEBUG: False
      DB_NAME: savannah_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -r requirements.txt
        pip install psycopg2-binary
        pip install drf-yasg

    - name: Create Static Directory
      run: |
        mkdir -p static

    - name: Wait for PostgreSQL
      run: |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            break
          fi
          if [ $i -eq 30 ]; then
            echo "PostgreSQL did not become ready in time"
            exit 1
          fi
          sleep 1
        done

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Run Tests
      run: |
        coverage run --source='.' manage.py test

    - name: Generate Coverage Report
      run: |
        coverage report -m

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/savannah-ecommerce:${{ env.IMAGE_TAG }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up minikube
      uses: medyagh/setup-minikube@master

    - name: Deploy to Kubernetes
      run: |
        # Create namespace if it doesn't exist
        kubectl create namespace savannah --dry-run=client -o yaml | kubectl apply -f -
        
        # Create secret for database password
        kubectl create secret generic db-secrets \
          --namespace savannah \
          --from-literal=password=postgres \
          --dry-run=client -o yaml | kubectl apply -f -
        
        # Apply Kubernetes manifests
        envsubst < k8s/deployment.yaml | kubectl apply -f -
        kubectl apply -f k8s/service.yaml
        
        # Wait for deployment to be ready
        kubectl rollout status deployment/savannah-ecommerce -n savannah
