# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Set dummy values for PostgreSQL variables at the job level
      # This might prevent accidental PostgreSQL connection attempts
      # if main settings.py is loaded prematurely.
      DB_USER: ''
      DB_PASSWORD: ''
      DB_HOST: ''
      DB_PORT: ''
      DJANGO_SETTINGS_MODULE: savannah_ecommerce.ci_settings
      DEBUG: False

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install tools for linting, formatting, coverage, security, and static analysis
        pip install flake8 black coverage pip-audit bandit dj-database-url

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Run Tests
      run: |
        coverage run --source='.' manage.py test

    - name: Generate Coverage Report
      run: |
        coverage report -m

    - name: Run Flake8 Linting
      run: flake8 .

    - name: Run Black Formatter Check
      run: black --check .

    - name: Run Pip-Audit Security Scan
      run: pip-audit

    - name: Run Bandit Static Analysis
      run: bandit -r . 
