# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: savannah_db
        ports:
          - 5432:5432
        # Add these settings to ensure PostgreSQL is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PYTHONPATH: ${{ github.workspace }}
      DJANGO_SETTINGS_MODULE: savannah_ecommerce.ci_settings
      DEBUG: False
      DB_NAME: savannah_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2-binary

    - name: Create Static Directory
      run: |
        mkdir -p static

    - name: Wait for PostgreSQL
      run: |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            break
          fi
          if [ $i -eq 30 ]; then
            echo "PostgreSQL did not become ready in time"
            exit 1
          fi
          sleep 1
        done

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Run Tests
      run: |
        coverage run --source='.' manage.py test

    - name: Generate Coverage Report
      run: |
        coverage report -m
